[2024-05-11T12:35:11.335+0000] {processor.py:153} INFO - Started process (PID=81) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py
[2024-05-11T12:35:11.340+0000] {processor.py:743} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2024-05-11T12:35:11.342+0000] {logging_mixin.py:137} INFO - [2024-05-11T12:35:11.342+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py
[2024-05-11T12:35:11.707+0000] {processor.py:753} INFO - DAG(s) dict_keys(['example_sensor_decorator']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py
[2024-05-11T12:35:12.186+0000] {logging_mixin.py:137} INFO - [2024-05-11T12:35:12.186+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:example_sensor_decorator
[2024-05-11T12:35:12.242+0000] {logging_mixin.py:137} INFO - [2024-05-11T12:35:12.242+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:example_sensor_decorator
[2024-05-11T12:35:12.270+0000] {logging_mixin.py:137} INFO - [2024-05-11T12:35:12.270+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:example_sensor_decorator
[2024-05-11T12:35:12.271+0000] {logging_mixin.py:137} INFO - [2024-05-11T12:35:12.271+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-11T12:35:12.320+0000] {logging_mixin.py:137} INFO - [2024-05-11T12:35:12.319+0000] {dag.py:2711} INFO - Creating ORM DAG for example_sensor_decorator
[2024-05-11T12:35:12.361+0000] {logging_mixin.py:137} INFO - [2024-05-11T12:35:12.360+0000] {dag.py:3441} INFO - Setting next_dagrun for example_sensor_decorator to None, run_after=None
[2024-05-11T12:35:12.422+0000] {processor.py:175} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py took 1.104 seconds
[2024-05-11T12:35:46.573+0000] {processor.py:153} INFO - Started process (PID=153) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py
[2024-05-11T12:35:46.649+0000] {processor.py:743} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2024-05-11T12:35:46.719+0000] {logging_mixin.py:137} INFO - [2024-05-11T12:35:46.707+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py
[2024-05-11T12:35:47.205+0000] {processor.py:753} INFO - DAG(s) dict_keys(['example_sensor_decorator']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py
[2024-05-11T12:35:47.468+0000] {logging_mixin.py:137} INFO - [2024-05-11T12:35:47.467+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-11T12:35:47.721+0000] {logging_mixin.py:137} INFO - [2024-05-11T12:35:47.720+0000] {dag.py:3441} INFO - Setting next_dagrun for example_sensor_decorator to None, run_after=None
[2024-05-11T12:35:47.840+0000] {processor.py:175} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py took 1.366 seconds
[2024-05-11T12:36:18.530+0000] {processor.py:153} INFO - Started process (PID=215) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py
[2024-05-11T12:36:18.538+0000] {processor.py:743} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py for tasks to queue
[2024-05-11T12:36:18.555+0000] {logging_mixin.py:137} INFO - [2024-05-11T12:36:18.554+0000] {dagbag.py:538} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py
[2024-05-11T12:36:19.089+0000] {processor.py:753} INFO - DAG(s) dict_keys(['example_sensor_decorator']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_sensor_decorator.py
[2024-05-11T12:36:19.442+0000] {logging_mixin.py:137} INFO - [2024-05-11T12:36:19.442+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-11T12:36:19.548+0000] {logging_mixin.py:137} INFO - [2024-05-11T12:36:19.548+0000] {dag.py:3441} INFO - Setting next_dagrun for example_sensor_decorator to None, run_after=None
[2024-05-11T12:36:41.613+0000] {processor.py:178} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1089, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 686, in do_commit
    dbapi_connection.commit()
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 174, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 158, in _handle_dag_file_processing
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/processor.py", line 769, in process_file
    session.commit()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 836, in commit
    trans.commit()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2459, in commit
    self._do_commit()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2649, in _do_commit
    self._connection_commit_impl()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2620, in _connection_commit_impl
    self.connection._commit_impl()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1091, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1089, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 686, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

(Background on this error at: https://sqlalche.me/e/14/e3q8)
